### ISSUE TITLE
Enhancement in Contact page

### ISSUE THREAD

**Issue by deepdarshan21** [deepdarshan21/bhaukaalnews#10]
There is some error in CSS of "Get In Touch" box of contact page
try to make it like https://deepdarshan21.github.io/bhaukaalnews/pages/contact.html this page

**Comment by deepdarshan21** [comment]
@rajraman786 please do it...as you did in  previous repo

**Comment by rajraman786** [comment]
@deepdarshan21 bug fixed( #16  ) go and check
