### ISSUE TITLE
# Covid19 tracker Mobile view issue

### ISSUE THREAD

**Issue by vedantgoswami** [deepdarshan21/bhaukaalnews#14]
The column where the total cases are mentioned get merged in mobile view.
Fix this bug....

**Comment by rajraman786** [comment]
@vedantgoswami go on

**Comment by rajraman786** [comment]
@vedantgoswami @deepdarshan21 if it's done now then kidly close this issue.

**Comment by rajraman786** [comment]
@vedantgoswami @deepdarshan21 if it's done now then kidly close this issue.

**Comment by deepdarshan21** [comment]
Haven't done yet
