### ISSUE TITLE
In Covid19 page, Make the value in thousand seperated format

### ISSUE THREAD

**Issue by vedantgoswami** [deepdarshan21/bhaukaalnews#21]

**Comment by deepdarshan21** [comment]
@vedantgoswami u don't understand the problem in **To reproduce** section

**Comment by vedantgoswami** [comment]
please explain a bit?

**Comment by deepdarshan21** [comment]
mareko bas heading samaj aai uske under discription kuch samaj nahi aaya

**Comment by vedantgoswami** [comment]
the values of confirmed,active,recovered and death are simple number but i need them to seperated like **21,000 or 1,30,000.**

**Comment by deepdarshan21** [comment]
@vedantgoswami I have solved this issue...please confirm that is it ok or I have to do something else

**Comment by vedantgoswami** [comment]
> @vedantgoswami I have solved this issue...please confirm that is it ok or I have to do something else

@deepdarshan21   Great piece of work done by you. I am feeling great to be working with you
